import 'package:yes_or_not_app/domain/entities/message.dart';

// Generated by QuickType: https://app.quicktype.io/
class YesNoModel {
  final String answer;
  final bool forced;
  final String image;

  YesNoModel({required this.answer, required this.forced, required this.image});

  factory YesNoModel.fromJsonMap(Map<String, dynamic> json) => YesNoModel(
    answer: json['answer'],
    forced: json['forced'],
    image: json['image'],
  );

  Map<String, dynamic> toJson() => {
    'answer': answer,
    'forced': forced,
    'image': image,
  };
  // End generated

  Message toMessageEntity() => Message(
    text: answer == 'yes' ? 'Sí' : 'No',
    fromWho: FromWho.her,
    imageUrl: image,
  );
}
